apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
  namespace: foursys-bigdata-poc
  labels:
    app: foursys-mysql-metastore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi