apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-deployment
  namespace: safrapay-bigdata-poc
  labels:
    app: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      volumes:
      - name: fileshare-dls
        azureFile:
          secretName: storage-secret-dls
          shareName: nifi
          readOnly: false
      containers:
      - name: safrapay-dataproc-nifi
        image: apache/nifi:latest
        ports:
        - containerPort: 8080
        env:
          - name: NIFI_WEB_HTTP_PORT
            value: "8080"
        resources: {}
        volumeMounts:
          - name: fileshare-dls
            mountPath: /opt/nifi/nifi-current/nifi-test-file/