apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: exerc01-load-balancer
  name: exerc01
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: exerc01-load-balancer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exerc01-load-balancer
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080